function T = rotate_matrix(theta, phi)
    % 自由旋转链中相邻两个局部坐标系的变换矩阵 
    r1 = [cos(phi) -sin(phi) 0.0; ...
          sin(phi) cos(phi) 0.0;  ...
          0.0 0.0 1.0];
    r2 = [cos(theta) 0.0 sin(theta); ...
          0.0 1.0 0.0; ...
          -sin(theta) 0.0 cos(theta)];
    T = r1 * r2;
end